---
title: "Modelos Matemáticos en Ecología I"
author: "Gerardo Martín"
date: "6/8/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Encuadre

## Sobre mí

- Gerardo Martín
    
    - Veterinario por ULSA Bajío
    - Maestro en Biología de Conservación por el INECOL A. C.
    - Doctor en Salud Pública por James Cook University
        - Posdoc en Imperial College London
        
## ¿Por qué un veterinario da MME-I?

1. Ivestigación cuantitativa

    1.1. Estadística y Matemáticas
    1.2. Problemas en salud pública que involucran a la ecología
    
2. Las matemáticas que uso son más o menos sencillas

    2.1. Simular transmissión de enfermedades
    2.2. Probar hipótesis sobre mecanismos de transmisión (directa vs indirecta)
    
Más info en mi sitio personal (aún en construcción!):

- [gerardommc.github.io](https://gerardommc.gihub.io)
    
## Sobre ustedes

1. ¿Por qué quieren estudiar ecología?
2. ¿Qué esperan de la universidad?
3. ¿Cómo puedo ayudar yo en su paso por aquí?
4. ¿Qué se imaginan haciendo profesionalmente como ecólogos?

# Sobre la materia

## ¿Cómo se darán las clases?

1. Mantener actividades sincrónicas al mínimo posible
    1.1. Tendremos más clases por zoom para los temas más complicados
    1.2. Lun-Jue: teoría y práctica
    1.3. Vie: dudas, repaso y discusión

2. Todos los contenidos del curso estarán en el sitio:

- [gerardommc.github.io/Modelos-matematicos-ECO-I/](https://gerardommc.github.io/Modelos-matematicos-ECO-I/)

3. Clases estarán basadas en el sitio
    
    3.1. Google Classroom

## Reglas 


1. Micrófonos apagados
2. Cámaras prendidas, excepto: 
    
    2.1. Velocidad de internet limitada 
    2.2. Datos limitados

3. Hacer muchas preguntas
4. Decirme si paso algo por alto

## Criterios de evaluación

1. *Asistencia* (25%)
2. Trabajos de clase (50%)
3. Examen (25%)
4. Participación (2 puntos extra máximo)
    4.1. En sesiones sincrónicas
    4.2. Preguntas por email en Classroom

## Sobre la *asistencia*

- No se califica presencia en sesiones sincrónicas
- Sí el cumplimiento de trabajos

# Sobre el curso

## ¿Qué aprenderemos?

1. Introducción a la modelación

    1.1. ¿Qué son, para qué y como desarrollamos los modelos?
    
2. Introducción a los modelos determinísticos
3. Cálculo diferencia e integral
4. Modelos deterministas
5. Introducción al álgebra matricial
6. Modelos de poblaciones estructuradas

## Contacto

- E-mail: [gerardo.mmc@enesmerida.unam.mx](mailto:gerardo.mmc@enesmerida.unam.mx)
- Sitio web personal: [gerardommc.github.io](https://gerardommc.github.com)
- Twitter: [@MmcGerardo](https://twitter.com/MmcGerardo)


