# Encuadre de la materia

## Criterios de evaluación

Las constribuciones a cada calificación parcial serán:

- Asistencia (25%)
- Trabajos de clase cumplidos (50%)
- Examen (25%)
- Participación (2 puntos extra máximo) 

Cabe señalar, que la asistencia no corresponderá con su presencia en las sesiones sincrónicas, sino con el cumplimiento de los trabajos de clase. La participación se medirá tanto por participación directa en las sesiones sincrónicas como por el seguimiento que uds den a la clase por correo electrónico.

## ¿Cómo se darán las clases?

Todos los contenidos del curso, lecturas y presentaciones, se irán añadiendo a este sitio web conforme avanza el semestre. En el Google Classroom de la materia se irán anunciando las diferentes actividades y sesiones sincrónicas con anticipación suficiente. Igualmente, los examenes y resultados serán publicados a través de esta plataforma. A petición de uds, también se publicarán aquí los videos de las sesiones sincrónicas que tengamos, en especial para aquellos temas que sean mayor interés/dificultad/importancia. Los trabajos de práctica también se publicarán en Classroom.

## Contacto

Para reportar fallos, resolver dudas y peticiones especiales grupales o individuales por favor enviar correo electrónico a [gerardo.mmc@enesmerida.unam.mx](mailto:gerardo.mmc@enesmerida.unam.mx).